services:
  foodpack:
    build:
      context: .
      args:
        QUARKUS_PROFILE: ${QUARKUS_PROFILE}
    container_name: foodpack
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    env_file:
      - .env
    environment:
      - QUARKUS_PROFILE=${QUARKUS_PROFILE}
    volumes:
      - ./logs:/app/logs
    restart: always
