########################
# Timefold Solver properties
########################

quarkus.datasource.devservices.enabled=false

%local.db.url=${DB_URL_LOCAL}
%dev.db.url=${DB_URL_DEV}
%prod.db.url=${DB_URL_PROD}
%brzprod.db.url=${DB_URL_BRZPROD}
%baranprod.db.url=${DB_URL_BARANPROD}


# Datasource
quarkus.datasource.db-kind=mssql
%local.quarkus.datasource.jdbc.url=${DB_JDBC_URL_LOCAL}
%dev.quarkus.datasource.jdbc.url=${DB_JDBC_URL_DEV}
%prod.quarkus.datasource.jdbc.url=${DB_JDBC_URL_PROD}
%brzprod.quarkus.datasource.jdbc.url=${DB_JDBC_URL_BRZPROD}
%baranprod.quarkus.datasource.jdbc.url=${DB_JDBC_URL_BARANPROD}
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}

# Hibernate ORM
quarkus.hibernate-orm.database.generation=none



# The solver runs for 30 seconds. To run for 5 minutes use "5m" and for 2 hours use "2h".
quarkus.timefold.solver.termination.spent-limit=10m

# To change how many solvers to run in parallel
quarkus.timefold.solver-manager.parallel-solver-count=6

# Temporary comment this out to detect bugs in your code (lowers performance)
# quarkus.timefold.solver.environment-mode=FULL_ASSERT

# Temporary comment this out to return a feasible solution as soon as possible
# quarkus.timefold.solver.termination.best-score-limit=0hard/0medium/*soft

# To see what Timefold is doing, turn on DEBUG or TRACE logging.
quarkus.log.category."ai.timefold.solver".level=INFO
%test.quarkus.log.category."ai.timefold.solver".level=INFO
%prod.quarkus.log.category."ai.timefold.solver".level=INFO

########################
# Timefold Solver Enterprise properties
########################

# To run increase CPU cores usage per solver
%enterprise.quarkus.timefold.solver.move-thread-count=AUTO

########################
# Native build properties
########################

# Enable Swagger UI also in the native mode
quarkus.swagger-ui.always-include=true

########################
# Test overrides
########################

# Effectively disable spent-time termination in favor of the best-score-limit
%test.quarkus.timefold.solver.termination.spent-limit=1h
%test.quarkus.timefold.solver.termination.best-score-limit=0hard/0medium/*soft

########################
# Profile settings
########################

## Localhost
%local.quarkus.http.port=8080
%local.quarkus.http.cors.origins=http://localhost:3000
%local.ksk=0119030000
%local.krc=170610000000
%local.krca=6000000

########################
# Hibernate SQL (local)
########################

%local.quarkus.hibernate-orm.log.sql=true
%local.quarkus.hibernate-orm.log.format-sql=true
%local.quarkus.hibernate-orm.log.bind-parameters=true

%local.quarkus.log.category."org.hibernate.SQL".level=DEBUG
%local.quarkus.log.category."org.hibernate.orm.query".level=DEBUG

## Developer 10.35.0.5
%dev.quarkus.http.port=8083
%dev.quarkus.http.cors.origins=${CORS_ORIGIN_DEV}
%dev.ksk=0119030000
%dev.krc=170610000000
%dev.krca=6000000

## Production 10.35.0.5
%prod.quarkus.http.port=8081
%prod.quarkus.http.cors.origins=${CORS_ORIGIN_PROD}
%prod.ksk=0119030000
%prod.krc=170610000000
%prod.krca=6000000

## Brz Production
%brzprod.quarkus.http.port=8081
%brzprod.quarkus.http.cors.origins=${CORS_ORIGIN_BRZPROD}
%brzprod.ksk=0119030000
%brzprod.krc=170610000000
%brzprod.krca=6000000

## Baran Production
%baranprod.quarkus.http.port=8081
%baranprod.quarkus.http.cors.origins=${CORS_ORIGIN_BARANPROD}
%baranprod.ksk=0127100000
%baranprod.krc=180606000000
%baranprod.krca=8080002

##### CORS #####################
quarkus.http.cors=true
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=
quarkus.http.cors.credentials=true


########################
# Logs Settings
########################

# --- Access log ---
%brzprod.quarkus.http.access-log.enabled=true
%brzprod.quarkus.http.access-log.pattern=common
%brzprod.quarkus.http.access-log.log-to-file=true
%brzprod.quarkus.http.access-log.base-file-name=logs/access
%brzprod.quarkus.http.access-log.rotate=true
%brzprod.quarkus.http.proxy.proxy-address-forwarding=true

# --- Application logs ---
# Console
quarkus.log.console.enable=true
quarkus.log.console.level=INFO
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{1.}] (%t) %s%e%n

# File
%brzprod.quarkus.log.file.enable=true
%brzprod.quarkus.log.file.path=logs/app.log
%brzprod.quarkus.log.file.level=INFO
%brzprod.quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{1.}] (%t) %s%e%n

# Rotate files
%brzprod.quarkus.log.file.rotation.max-file-size=10M
%brzprod.quarkus.log.file.rotation.max-backup-index=10
%brzprod.quarkus.log.file.rotation.file-suffix=.yyyy-MM-dd
