########################
# Timefold Solver properties
########################

quarkus.datasource.devservices.enabled=false

# Database URL (same for all profiles)
db.url=${DB_URL}
# Database schemes
app.mes.schema=${MES_SCHEMA}
app.prommark.schema=${PROMMARK_SCHEMA}
# Configuration codes (same for all profiles)
ksk=${KSK}
krc=${KRC}
krca=${KRCA}

# Datasource
quarkus.datasource.db-kind=mssql
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.http.port=${HTTP_PORT}

# Hibernate ORM
quarkus.hibernate-orm.database.generation=none

# The solver runs for 30 seconds. To run for 5 minutes use "5m" and for 2 hours use "2h".
quarkus.timefold.solver.termination.spent-limit=10m

# To change how many solvers to run in parallel
quarkus.timefold.solver-manager.parallel-solver-count=6

# Temporary comment this out to detect bugs in your code (lowers performance)
# quarkus.timefold.solver.environment-mode=FULL_ASSERT

# Temporary comment this out to return a feasible solution as soon as possible
# quarkus.timefold.solver.termination.best-score-limit=0hard/0medium/*soft

# To see what Timefold is doing, turn on DEBUG or TRACE logging.
quarkus.log.category."ai.timefold.solver".level=INFO
%test.quarkus.log.category."ai.timefold.solver".level=INFO
%prod.quarkus.log.category."ai.timefold.solver".level=INFO

########################
# Timefold Solver Enterprise properties
########################

# To run increase CPU cores usage per solver
%enterprise.quarkus.timefold.solver.move-thread-count=AUTO

########################
# Native build properties
########################

# Enable Swagger UI also in the native mode
quarkus.swagger-ui.always-include=true

########################
# Test overrides
########################

# Effectively disable spent-time termination in favor of the best-score-limit
%test.quarkus.timefold.solver.termination.spent-limit=1h
%test.quarkus.timefold.solver.termination.best-score-limit=0hard/0medium/*soft

########################
# Profile settings
########################

########################
# Hibernate SQL (local)
########################

%local.quarkus.hibernate-orm.log.sql=true
%local.quarkus.hibernate-orm.log.format-sql=true
%local.quarkus.hibernate-orm.log.bind-parameters=true

%local.quarkus.log.category."org.hibernate.SQL".level=DEBUG
%local.quarkus.log.category."org.hibernate.orm.query".level=DEBUG

##### CORS #####################
quarkus.http.cors.origins=${CORS_ORIGIN}
quarkus.http.cors=true
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=
quarkus.http.cors.credentials=true

########################
# Logs Settings
########################

# --- Application logs ---
# Console
quarkus.log.console.enable=true
quarkus.log.console.level=INFO
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{1.}] (%t) %s%e%n

# --- Production Access log ---
%prod.quarkus.http.access-log.enabled=true
%prod.quarkus.http.access-log.pattern=common
%prod.quarkus.http.access-log.log-to-file=true
%prod.quarkus.http.access-log.base-file-name=logs/access
%prod.quarkus.http.access-log.rotate=true
%prod.quarkus.http.proxy.proxy-address-forwarding=true

# --- Production File logs ---
%prod.quarkus.log.file.enable=true
%prod.quarkus.log.file.path=logs/app.log
%prod.quarkus.log.file.level=INFO
%prod.quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{1.}] (%t) %s%e%n

# Rotate files
%prod.quarkus.log.file.rotation.max-file-size=10M
%prod.quarkus.log.file.rotation.max-backup-index=10
%prod.quarkus.log.file.rotation.file-suffix=.yyyy-MM-dd